apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
  namespace: ticket-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
        - name: api
          image: ticket-api:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.ticket-mlops.svc.cluster.local:5000"
            - name: MODEL_URI
              value: "models:/ticket-router/Production"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

